### ISSUE TITLE
Using infix with variable string

### ISSUE THREAD

**Issue by DiegoMG88** [soegaard/infix#10]
i try to use the code:

#lang at-exp racket
(require infix)
(define txt "2+2")
@${ txt } or ($ "txt")

but the output it's the string "2+2" and not the evaluation @${2+2} or ($ "2+2") -> 4
it is posible to use a string as argument of $ to be evaluated as i need?

**Comment by soegaard** [comment]
Yes, you can call the parser directly:

```
> (require infix/parser)

> (parse-math-string "2+2")
#<syntax:/Users/soegaard/Library/Racket/7.5/pkgs/infix/infix/parser.rkt:346:41  (#%infix (+ 2 2))>

> (syntax->datum (parse-math-string "2+2"))
'(#%infix (+ 2 2))
```

**Comment by soegaard** [comment]
You can use `eval` to evaluate the expression:

```
> (eval (parse-math-string "2+2"))
4
```

**Comment by DiegoMG88** [comment]
Thank you so much, i tried with a little harder expression and works perfectly.

#lang at-exp racket
(require infix/parser)

(define txt "(λx y.x*y+5)")
(define f (eval (parse-math-string txt)))

(f 2 3) -> 11
